language: node_js
node_js:
- node
before_script:
- npm prune
script:
- npm run test
deploy:
  provider: npm
  email: mridevteam@gmail.com
  api_key:
    secure: Nxw/mGfuVLP9RbcrJ2FyrxXjREZR1yO0EbdT8NQD668NfmmsXVuvetZ2ZukbJonK+vbsJ179JjKytQI0JE0UgA6Z64HKNrrHHzOueioahJmW3oZNdUx9sBGE1FRiC54F9mCsqpxbjzUBhVD1Ag39BL+0/aCx6ht0WHFLPcRgzlxb+OvrCayVTWJ4qyPV8CN76xb1vcyMLxd6qe/ChFU8dX0wfKp36MbSgHJX2l7EnHLG6J2EUBRDnPMgsSYgRoWyF6JlJjz7+Lmdv5nLM4TInhF1+u1rUQ1dcYHkmFhusk0LQptkU6ys9n3lRXvoqWjLa62Bz49ztNmRe4rY3FzFXkRD2+qle71MxsMS/O3iLMSwYESJOpVdVJAc41tatytTX9ZuPchYqGm5PsN0OCncg9dQn/mSX//+/NbhlZptbg0A5vEWl+eZ2w3TT3+rm012iYVIsquzb82+Gh54hBVI6WapmeZNA3Vcl9PGxCVvImhiWOWshpOQT7anmKDfhRN8XT1Tuh0y9aoJAaBdjQfj3lT/syAXjmqj6H1KiiIMr4jsXBmXnvRzH5YI+Mu3fwGJy4PO3xdYJFrN0xIwsY5qCRoT3lEIb1hXDlhIgPmsul+rS/9Q298TUr1/vlowCr1AKB60tB8G+Qo3Al7cWyF8yvz4aOpLRAPX2R2XpN65K6I=
  on:
    tags: true
    repo: mridevteam/date_utils
